### ISSUE TITLE
errors showing in console during general use

### ISSUE THREAD

**Issue by svidgen** [svidgen/mtg.deckanalyzer.com-Feedback#47]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'legalities')
    at rulings.js:37:23
    at Array.map (<anonymous>)
    at rulings.js:34:34
    at e.exports.DomClass.show (rulings.js:46:3)
    at rulings.js:54:7
```

I'm not seeing the meaningful impact of this yet. But, something is wrong. So, it should be fixed!

**Comment by svidgen** [comment]
Pretty sure this is resolved. Closing.
